FROM ollama/ollama

WORKDIR /app

# Copy the start script into the container
COPY ollama_model_pull.sh /app/ollama_model_pull.sh

# Ensure the script is executable
RUN chmod +x /app/ollama_model_pull.sh

# Run the script
RUN /app/ollama_model_pull.sh